CONFIG_BT=y
CONFIG_BT_DEVICE_NAME="G4y_CapVersion"
##CONFIG_BT_CTLR_TX_PWR_MINUS_4=y  #Set the TX power
CONFIG_BT_LL_SW_SPLIT=n
CONFIG_BT_CTLR_ADVANCED_FEATURES=y
CONFIG_BT_CTLR_TX_PWR_DYNAMIC_CONTROL=y
CONFIG_REBOOT=y


CONFIG_I2C=y
CONFIG_I2C_NRFX=y
CONFIG_GPIO=y
CONFIG_SPI=y
CONFIG_PINCTRL=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y

CONFIG_LOG=n
CONFIG_SERIAL=n
CONFIG_STDOUT_CONSOLE=n


CONFIG_PM=y
CONFIG_PM_DEVICE=y
CONFIG_PM_DEVICE_RUNTIME=y
CONFIG_PM_S2RAM=n


CONFIG_DEBUG_OPTIMIZATIONS=n
CONFIG_DEBUG_THREAD_INFO=n
CONFIG_GPIO_AS_PINRESET=n

