CONFIG_BT=y
CONFIG_BT_DEVICE_NAME="G4y_CapVersion_DB"
##CONFIG_BT_CTLR_TX_PWR_MINUS_4=y  #Set the TX power
CONFIG_BT_LL_SW_SPLIT=y
CONFIG_BT_CTLR_ADVANCED_FEATURES=y
CONFIG_BT_CTLR_TX_PWR_DYNAMIC_CONTROL=y


CONFIG_I2C=y
CONFIG_I2C_NRFX=y
CONFIG_GPIO=y
CONFIG_SPI=y
CONFIG_PINCTRL=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y

# Enable RTT to replace UART
CONFIG_STDOUT_CONSOLE=y
CONFIG_UART_CONSOLE=n
CONFIG_USE_SEGGER_RTT=y
CONFIG_SHELL_BACKEND_RTT=y

#CONFIG_BT_DEBUG_LOG=n
CONFIG_LOG=y
CONFIG_SERIAL=y
CONFIG_STDOUT_CONSOLE=n

CONFIG_PM=y
CONFIG_PM_DEVICE=y
#CONFIG_PM_S2RAM=n
#CONFIG_PM_DEVICE_RUNTIME=y

CONFIG_DEBUG_OPTIMIZATIONS=y
CONFIG_DEBUG_THREAD_INFO=y
CONFIG_GPIO_AS_PINRESET=n
